### ISSUE TITLE
Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by avatar-lavventura** [giovtorres/docker-centos7-slurm#44]
Thank you for your work. I tried to convert the Dockerfile in ubuntu format.

But I keep getting following error from `mysql`:

```
$ /usr/bin/mysqld_safe
220422 10:39:58 mysqld_safe Logging to syslog.
220422 10:39:58 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
$ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)
```

Do you have any idea how could this be solved?

**Comment by giovtorres** [comment]
I'm not sure if what's in this project can be directly transposed to Ubuntu without some tweaking. It appears MySQL is not starting up properly. I would check the MySQL logs for clues.

**Comment by avatar-lavventura** [comment]
I have build in top of `FROM python:3.7`, I believe its `Debian`. I have done some tweaking :-) 

This is what I have right now: https://github.com/ebloc/ebloc-broker/blob/dev/broker/_slurm/Dockerfile

Thanks I will look into the MySQL logs.

**Comment by avatar-lavventura** [comment]
I was able to make it work in ubuntu. Not related to mysql but for munge I had to do:

```RUN chown root:munge -R /etc/munge /etc/munge/munge.key /var/lib/munge```
