### ISSUE TITLE
Connecting to pyslurm

### ISSUE THREAD

**Issue by jakwall** [giovtorres/docker-centos7-slurm#6]
Hello Giovanni! 

I find this docker container really useful and I am interested to use this for development with pyslurm as well. I am not sure how to connect the two though. I can not install pyslurm with "pip install pyslurm" inside this container. Do you have any suggestions about how to make it work with this (the Slurm headers and libraries) and pyslurm?

Have a nice day!
Jakob

**Comment by jakwall** [comment]
Trying to install pyslurm through cloning the package from git I get the message that I am using slurm version 19 and that pyslurm only works for slurm 17/18. Do you know if there is a way to walk around this?

**Comment by giovtorres** [comment]
When inside the container, use git to clone, then checkout the right branch, then run `python setup.py build && python setup.py install`.

**Comment by jakwall** [comment]
I had Slurm version 19 but I now saw that I could tag the docker for previous versions. When I use version 18.08.7 it works to run "pip install pyslurm", so problem solved.
Thank you for your help!
